easy_admin:
    entities:
        User:
            class: App\Entity\User
            label: User
            list:
                fields:
                    - { property: username }
                    - { property: password }
                    - { property: isAdmin }
            form:
                fields:
                    - { property: username }
                    - { property: password }
                    - { property: isAdmin }
        Filament:
            class: App\Entity\Filament
            label: Filament
            list:
                fields:
                    - { property: name }
                    - { property: weight, label: 'Weight (g)' }
                    - { property: price, label: 'Price (€)' }
                    - { property: density, label: 'Density (g/cm³)' }
                    - { property: diameter, label: 'Diameter (mm)' }
            form:
                fields:
                    - { property: name }
                    - { property: weight, label: 'Weight (g)' }
                    - { property: price, label: 'Price (€)' }
                    - { property: density, label: 'Density (g/cm³)' }
                    - { property: diameter, label: 'Diameter (mm)' }
        PrintItem:
            class: App\Entity\PrintItem
            label: PrintItem
            list:
                fields:
                    - { property: user }
                    - { property: name }
                    - { property: link, type: 'url' }
                    - { property: filament }
                    - { property: quantity }
                    - { property: weight }
                    - { property: isPrinted }
            form:
                fields:
                    - { property: user }
                    - { property: name }
                    - { property: link }
                    - { property: filament }
                    - { property: comment }
                    - { property: quantity }
                    - { property: weight }
                    - { property: createdAt, type_options: {disabled: true} }
