version: '3.7'

volumes:
    builder-data: {}

services:
    php-base:
        build: services/php-base

    builder:
        build: services/builder
        depends_on:
            - postgres
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        volumes:
            - "../../${PROJECT_DIRECTORY}:/home/app/application:cached"
            - "${COMPOSER_CACHE_DIR}:/home/app/.composer/cache"
            - "../../invoke.py:/home/app/invoke.py"
            - "../../tasks.py:/home/app/tasks.py"
            - "builder-data:/home/app"
