easy_admin:
    site_name: '3D Follow'
    design:
        menu:
            - { entity: 'PrintObject', icon: 'file-code-o', default: true }
            - { entity: 'PrintRequest', icon: 'list' }
            - { entity: 'Filament', icon: 'circle-notch' }
            - { entity: 'User', icon: 'user' }
            - { entity: 'Team', icon: 'users' }
    entities:
        User:
            class: App\Entity\User
            label: User
            list:
                fields:
                    - { property: username }
                    - { property: isPrinter }
                    - { property: isAdmin }
                    - { property: createdAt }
                    - { property: teams.count, label: "Teams" }
            form:
                fields:
                    - { property: username }
                    - { property: isPrinter }
                    - { property: isAdmin }
                    - { property: createdAt, type_options: {disabled: true} }
                    - { property: teams }
        Team:
            class: App\Entity\Team
            label: Team
            list:
                fields:
                    - { property: creator }
                    - { property: members.count, label: "Members" }
                    - { property: joinToken }
            form:
                fields:
                    - { property: creator }
                    - { property: members }
        Filament:
            class: App\Entity\Filament
            label: Filament
            list:
                fields:
                    - { property: owner }
                    - { property: name }
                    - { property: weight, label: 'Weight (g)' }
                    - { property: price, label: 'Price (€)' }
                    - { property: density, label: 'Density (g/cm³)' }
                    - { property: diameter, label: 'Diameter (mm)' }
            form:
                fields:
                    - { property: owner }
                    - { property: name }
                    - { property: weight, label: 'Weight (g)' }
                    - { property: price, label: 'Price (€)' }
                    - { property: density, label: 'Density (g/cm³)' }
                    - { property: diameter, label: 'Diameter (mm)' }
                    - { property: comment }
        PrintRequest:
            class: App\Entity\PrintRequest
            label: Print request
            list:
                fields:
                    - { property: team }
                    - { property: user }
                    - { property: name }
                    - { property: link, type: 'url' }
                    - { property: quantity }
                    - { property: isPrinted }
            form:
                fields:
                    - { property: team }
                    - { property: user }
                    - { property: name }
                    - { property: link }
                    - { property: comment }
                    - { property: quantity }
                    - { property: printObjects }
                    - { property: createdAt, type_options: {disabled: true} }
        PrintObject:
            class: App\Entity\PrintObject
            label: Print object
            list:
                fields:
                    - { property: user }
                    - { property: name }
                    - { property: filament }
                    - { property: quantity }
                    - { property: cost }
            form:
                fields:
                    - { property: user }
                    - { property: name }
                    - { property: filament }
                    - { property: gCodeFile, type: 'vich_file' }
                    - { property: quantity }
                    - { property: weight }
                    - { property: length }
                    - { property: cost }
                    - { property: printRequest }
                    - { property: printedAt }
